name: Deploy Next.js (Metode ZIP)

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸš€ Build, Zip, & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Ambil Kode
      uses: actions/checkout@v4

    - name: ðŸŸ¢ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: ðŸ“¦ Build & Bungkus (Zip)
      run: |
        npm install
        # Matikan cek error agar build lancar
        export NEXT_PUBLIC_IGNORE_BUILD_ERRORS=true
        npm run build
        
        # Buat folder sementara untuk menampung file siap kirim
        mkdir siap_kirim
        
        # Masukkan file penting ke dalam ZIP
        # Kita pakai wildcard next.config.* jaga-jaga kalau namanya .js/.mjs/.ts
        zip -r siap_kirim/paket_website.zip .next public package.json next.config.*
        
    - name: ðŸ“‚ Upload ZIP ke Hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        security: loose
        
        # Upload ISI dari folder siap_kirim (yaitu file zip saja)
        local-dir: ./siap_kirim/
        server-dir: ./platform-utbk/aplikasi-cbt/