name: Deploy Next.js ke Hosting

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸš€ Deploy Files
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Ambil Kode Terbaru
      uses: actions/checkout@v4

    - name: ðŸ“‚ Upload ke Hosting via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        security: loose
        
        # INI KUNCI PERBAIKANNYA:
        # Kita suruh dia masuk ke folder aplikasi-cbt sebelum upload
        server-dir: ./aplikasi-cbt/
        
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.next/**
          **/.env*