name: Deploy Next.js (Build di GitHub)

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸš€ Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Ambil Kode
      uses: actions/checkout@v4

    - name: ðŸŸ¢ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: ðŸ“¦ Install & Build di GitHub
      run: |
        npm install
        # Kita matikan cek error saat build biar lancar
        export NEXT_PUBLIC_IGNORE_BUILD_ERRORS=true
        npm run build

    - name: ðŸ“‚ Upload ke Hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        security: loose
        server-dir: ./platform-utbk/aplikasi-cbt/
        
        # PENTING: Kita upload folder .next (hasil build), tapi TIDAK upload node_modules (berat)
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*